

site_name: Documentação
site_description: Repositório da disciplina EPS/MDS
repo_url: https://github.com/lmmLucasMachado/test
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://fga-disciplinas.github.io/2019.1-Guia-Bolso/">Requisitos 2019.1</a>.
dev_addr: ‘0.0.0.0:8000
theme:
  name: 'material'

  palette:
    primary: grey
    accent: black
    language: 'pt'

plugins:
  - search

page:
- Home: 'docs/index.md'